services:
  mariadb:
    image: mariadb@sha256:1e669024fc94f626b9dc48bf47b29b5339cec203c28e61a3dc372991a345daf5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - tfpwa
  wordpress:
    build:
      context: .docker/wordpress
      dockerfile: Dockerfile
      args:
        VERSION: ${WP_VERSION:-php8.0}
    depends_on:
      - mariadb
    ports:
      - 8443:443
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mariadb
    volumes: &ref_0
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/two-factor-provider-webauthn
    networks:
      - tfpwa
  cli:
    image: wordpress:cli-php8.3@sha256:c315889551f5b03e1fb3f3283d2cd2a1bad08f46baded35d57c9201bba65964d
    volumes: *ref_0
    user: '33:33'
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mariadb
    networks:
      - tfpwa

networks:
  tfpwa:
volumes:
  mysql:
  wordpress:
