version: '3.7'

services:
  mariadb:
    image: mariadb@sha256:bfc25a68e113de43d0d112f5a7126df8e278579c3224e3923359e1c1d8d5ce6e
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - tfpwa
  wordpress:
    build:
      context: .docker/wordpress
      dockerfile: Dockerfile
      args:
        VERSION: ${WP_VERSION:-php8.0}
    depends_on:
      - mariadb
    ports:
      - 8443:443
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mariadb
    volumes: &ref_0
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/two-factor-provider-webauthn
    networks:
      - tfpwa
  cli:
    image: wordpress:cli-php8.0@sha256:fbe5ba89d492b50c406e8cdfb76456d273a0087228dca3c6d9825ab49edb1375
    volumes: *ref_0
    user: '33:33'
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mariadb
    networks:
      - tfpwa

networks:
  tfpwa:
volumes:
  mysql:
  wordpress:
